name = "pharmacy-pos"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXTAUTH_URL = "https://pharmacy-pos.pages.dev"
